sonar.projectKey=prioritest-s5-mlservice
sonar.projectName=S5-MLService
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**,**/models/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true

