sonar.projectKey=prioritest-s1-collectedepots
sonar.projectName=S1-CollecteDepots
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**,**/alembic/**,**/migrations/**
sonar.test.exclusions=**/tests/**
sonar.coverage.exclusions=**/__init__.py,**/models/**,**/database/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true

