sonar.projectKey=prioritest-s0-apigateway
sonar.projectName=S0-ApiGateway
sonar.projectVersion=1.0.0
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.java.target=17
sonar.exclusions=**/generated/**,**/target/**
sonar.test.exclusions=**/test/**
sonar.qualitygate.wait=true

