sonar.projectKey=prioritest-s4-pretraitementfeatures
sonar.projectName=S4-PretraitementFeatures
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**,**/feature_repo/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true

