sonar.projectKey=prioritest-s7-testscaffolder
sonar.projectName=S7-TestScaffolder
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**,**/templates/**
sonar.test.exclusions=**/tests/**
sonar.coverage.exclusions=**/__init__.py,**/models/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true

