package com.testprioritization.model.response;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Automatic comment generated for PR/MR with risk analysis.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PRComment {

    private String comment;
    private String markdownBody;
    
    @JsonProperty("risk_summary")
    private RiskSummary riskSummary;
    
    @JsonProperty("recommendations")
    private List<Recommendation> recommendations;
    
    @JsonProperty("test_scaffolder_link")
    private String testScaffolderLink;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class RiskSummary {
        @JsonProperty("total_files_modified")
        private Integer totalFilesModified;
        
        @JsonProperty("high_risk_count")
        private Integer highRiskCount;
        
        @JsonProperty("medium_risk_count")
        private Integer mediumRiskCount;
        
        @JsonProperty("low_risk_count")
        private Integer lowRiskCount;
        
        @JsonProperty("tests_coverage_status")
        private String testsCoverageStatus;
        
        @JsonProperty("overall_risk_level")
        private String overallRiskLevel;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Recommendation {
        private String type;
        private String priority;
        private String message;
        
        @JsonProperty("target_class")
        private String targetClass;
        
        @JsonProperty("suggested_action")
        private String suggestedAction;
        
        @JsonProperty("action_url")
        private String actionUrl;
    }

    /**
     * Generate formatted markdown comment for GitHub/GitLab.
     */
    public String toMarkdown() {
        StringBuilder sb = new StringBuilder();
        
        // Header
        sb.append("## 🔍 Test Prioritization Analysis\n\n");
        
        // Risk Summary Table
        if (riskSummary != null) {
            sb.append("### Risk Summary\n\n");
            sb.append("| Metric | Value |\n");
            sb.append("|--------|-------|\n");
            sb.append(String.format("| Files Modified | %d |\n", 
                riskSummary.getTotalFilesModified() != null ? riskSummary.getTotalFilesModified() : 0));
            sb.append(String.format("| 🔴 High Risk Classes | %d |\n", 
                riskSummary.getHighRiskCount() != null ? riskSummary.getHighRiskCount() : 0));
            sb.append(String.format("| 🟡 Medium Risk Classes | %d |\n", 
                riskSummary.getMediumRiskCount() != null ? riskSummary.getMediumRiskCount() : 0));
            sb.append(String.format("| 🟢 Low Risk Classes | %d |\n", 
                riskSummary.getLowRiskCount() != null ? riskSummary.getLowRiskCount() : 0));
            sb.append(String.format("| Overall Risk | **%s** |\n\n", 
                riskSummary.getOverallRiskLevel() != null ? riskSummary.getOverallRiskLevel() : "Unknown"));
        }
        
        // Recommendations
        if (recommendations != null && !recommendations.isEmpty()) {
            sb.append("### Recommendations\n\n");
            for (Recommendation rec : recommendations) {
                String emoji = getEmojiForPriority(rec.getPriority());
                sb.append(String.format("%s **%s**: %s\n", emoji, rec.getType(), rec.getMessage()));
                if (rec.getTargetClass() != null) {
                    sb.append(String.format("   - Target: `%s`\n", rec.getTargetClass()));
                }
                if (rec.getSuggestedAction() != null) {
                    sb.append(String.format("   - Action: %s\n", rec.getSuggestedAction()));
                }
                sb.append("\n");
            }
        }
        
        // Test Scaffolder Link
        if (testScaffolderLink != null) {
            sb.append(String.format("\n📋 [Generate Test Scaffolds](%s)\n", testScaffolderLink));
        }
        
        // Footer
        sb.append("\n---\n");
        sb.append("*Generated by Test Prioritization Service*");
        
        return sb.toString();
    }
    
    private String getEmojiForPriority(String priority) {
        if (priority == null) return "ℹ️";
        return switch (priority.toUpperCase()) {
            case "HIGH", "CRITICAL" -> "🚨";
            case "MEDIUM" -> "⚠️";
            case "LOW" -> "💡";
            default -> "ℹ️";
        };
    }
}

