# Feature definitions aligned with architecture specification
# Service 4: PretraitementFeatures - Feast Feature Store

from datetime import timedelta
from feast import Entity, FeatureService, FeatureView, Field, FileSource, PushSource, RequestSource
from feast.types import Float32, Int64, String

# Define entity for class (aligned with architecture spec)
# Entity: class_name + repository_id
class_entity = Entity(name="class", join_keys=["class_name", "repository_id"])

# Define the source of the data
# Pointing to the features.csv generated by the pipeline
# Note: In a real scenario, this might point to a parquet file or a data warehouse table
feature_source = FileSource(
    name="commit_features_source",
    path="../data/processed/features.parquet",  # Path relative to feature_repo
    timestamp_field="commit_date",
)

# Define the Feature View (aligned with architecture specification)
# Features include base metrics + derived features (churn, num_authors, bug_fix_proximity, etc.)
processed_features_view = FeatureView(
    name="processed_features",
    entities=[class_entity],
    ttl=timedelta(days=365),
    schema=[
        # Base metrics (from S2)
        Field(name="loc", dtype=Float32),
        Field(name="cyclomatic_complexity", dtype=Float32),
        Field(name="wmc", dtype=Float32),
        Field(name="cbo", dtype=Float32),
        # Derived features (from S4)
        Field(name="churn", dtype=Float32),
        Field(name="num_authors", dtype=Int64),
        Field(name="modification_frequency", dtype=Float32),
        Field(name="bug_fix_proximity", dtype=Float32),
        Field(name="age_days", dtype=Int64),
        Field(name="last_modified_days_ago", dtype=Int64),
        # Coverage features (from S3)
        Field(name="current_line_coverage", dtype=Float32),
        Field(name="coverage_trend", dtype=String),  # "increasing"|"decreasing"|"stable"
        Field(name="test_debt_score", dtype=Float32),
        # Encoded features
        Field(name="has_tests", dtype=Int64),
        Field(name="is_critical_module", dtype=Int64),
        Field(name="language", dtype=String),
    ],
    online=True,
    source=feature_source,
    tags={"team": "ml-ops", "service": "S4-PretraitementFeatures"},
)