sonar.projectKey=prioritest-s6-moteurpriorisation
sonar.projectName=S6-MoteurPriorisation
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**,**/alembic/**,**/migrations/**
sonar.test.exclusions=**/tests/**
sonar.coverage.exclusions=**/__init__.py,**/models/**,**/database/**
sonar.python.coverage.reportPaths=coverage.xml

# Quality Gate and Profile
sonar.qualitygate.wait=true
sonar.python.codeSmellThreshold=100
sonar.python.bugThreshold=10
sonar.python.vulnerabilityThreshold=0
sonar.python.duplicationThreshold=5
sonar.python.coverageThreshold=30

