sonar.projectKey=prioritest-s2-analysestatique
sonar.projectName=S2-AnalyseStatique
sonar.projectVersion=1.0.0
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.java.target=17
sonar.exclusions=**/generated/**,**/target/**
sonar.test.exclusions=**/test/**
sonar.coverage.exclusions=**/model/**,**/dto/**,**/config/**

# Quality Gate and Profile
sonar.qualitygate.wait=true
sonar.java.codeSmellThreshold=100
sonar.java.bugThreshold=10
sonar.java.vulnerabilityThreshold=0
sonar.java.duplicationThreshold=5
sonar.java.coverageThreshold=30

